project 'Safety First.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Safety First' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Safety First
  pod 'RealmSwift', "~> 3.0.1"
  pod 'Alamofire', "~> 4.5.1"
end
