project 'realm_demo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'realm_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for realm_demo
  pod 'RealmSwift', '~> 2.10.0'
end
